excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://johnkellden.github.io
title: Conversations That Mind And Matter
tagline: inquiry: ecosystemics, economy & eudaimonia
description: Conversation as an art through which human beings rediscover, rekindle, revitalize and respond - after which we align with the world, small moves, until here and now. 
paginate: 5